### PR TITLE
Bias the data relative to a chosen currency

### PR DESCRIPTION
**Pull request by eymiha**
Choosing a currency from the Bias select will put the currency on the zero line and adjust all of the currency gains/losses in the chart relative to it. Selecting the blank option on the Bias select restores the absolute currency gains/losses.

### CODE REVIEW

**Comment by benstr** [comment]
Neat! I can't wait to try this out... unfortunately it will have to wait until Friday evening unless one of the other comrades get to it first. Thanks @eymiha

**Comment by sircharleswatson** [comment]
@eymiha I just merged your other two PRs and it looks like there is a conflict with this one. Mind checking it out before we try to test your new functionality?

**Comment by eymiha** [comment]
That figures... the new code is around the other code I'd changed, but I was branching from master each time...

**Comment by eymiha** [comment]
This PR should be up to date with master now.

**Pull request closed without merging**
